### PR TITLE
Ukrainian translation update

### PR DESCRIPTION
**Pull request by laktiv**
+ new 'export' menu
+ styling terms updates
+ general fixes

### CODE REVIEW

**Comment by chrisgurney** [comment]
Hi @laktiv , thank you for your contributions! 

Right now I'm just waiting for the beta to stabilize before I review. I'm still refining text and the user experience around import/export/sharing, but after I will take a look at your text and let you know if there are any gaps. 

Thanks again!

**Comment by laktiv** [comment]
Hi @chrisgurney,
Thank you for your feedback. I've already saw your message regarding no new translations until import/export functionality will be finished. Looking for this functionality because I have several vaults and one toolbar is used in all of them.
Btw, where to it is better to post my suggestions, use cases, and bugs?
THa nkyou

**Comment by chrisgurney** [comment]
@laktiv
- For **suggestions** you can click _New discussion_ in the [Discussions tab](https://github.com/chrisgurney/obsidian-note-toolbar/discussions).
- For **bugs** you can click _New issue_ from the [Issues tab](https://github.com/chrisgurney/obsidian-note-toolbar/issues).

**Comment by chrisgurney** [comment]
Thanks for checking in, by the way. There's lots of new strings and iterations I've had to do to get importing/exporting/sharing working well.

**Comment by laktiv** [comment]
@chrisgurney I saw that :) btw, added latest translation already. I really love your addon ))

**Pull request closed without merging**
