### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by hartimd**
I think I did everything in the translation instructions. If not, let me know.

### CODE REVIEW

**Comment by chrisgurney** [comment]
@hartimd Thank you so much! I'll take a look when I get a chance!

Can you restore the original `en.json` file, so it's not deleted in this PR? Thanks!

**Comment by chrisgurney** [comment]
@hartimd Don't worry about my comment. I'm merging your changes manually now; should be live shortly. Thanks again!

**Comment by hartimd** [comment]
Please ignore the recent pull request.
I just sw your comment :)

**Comment by chrisgurney** [comment]
Your changes are now live in the beta. I merged them manually.

**Pull request closed without merging**
