### PR TITLE
Add Chinese Simplified Language for CSS Settings

### PR DESCRIPTION
**Pull request by Moyf**
image

BTW, I helped fixing some of the `de` lang problems 😄

### CODE REVIEW

**Comment by chrisgurney** [comment]
Thanks @Moyf ! I've manually merged this, and will be in the next release. Thanks for your help!

**Comment by Moyf** [comment]
Hi @chrisgurney !
Since the "Quick Tools"'s name has been changed, I think we could also update the Chinese:
image

快速工具 -> 快速工具栏

Just replace in those 2 places, I think.

And for the tool's settings:
image

Only here ↑

**Comment by Moyf** [comment]
BTW, it seems that the "label" and "icon" hasn't been tranlated, did I miss something?
image

If so, could you help adding it?
label: `仅文本`
icon: `仅图标`

**Comment by Moyf** [comment]
> > quick tools: 快速工具
> > quick toolbar: 快速工具栏
> 
> Thanks! Can you include the word "Open"? As in "Open quick tools" and "Open quick toolbar"?
> 
> > BTW, it seems that the "label" and "icon" hasn't been tranlated, did I miss something?
> 
> Thanks for reporting this! It's been fixed in the next version; wasn't a missing string.

Of course!
Open quick tools = 打开快速工具
Open quick toolbar = 打开快速工具栏

**Pull request closed without merging**
